---
# file: roles/pacemaker/tasks/main.yml
- include: destroy.yml
  when: pacemaker_destroy_cluster is defined and pacemaker_destroy_cluster == true

- include: install.yml
- include: firewall.yml
  when: pacemaker_firewalld is defined and pacemaker_firewalld == true

- include: user.yml
- include: auth.yml
- include: sync.yml
- include: start.yml

- include: properties.yml
